apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-filter-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-filter-app
  template:
    metadata:
      labels:
        app: image-filter-app
    spec:
      containers:
      - name: image-filter-app
        image: real101/image-filter-app:latest
        ports:
        - containerPort: 5000
